---
- name: Install RequestHeader Oauth Config in master-config.yaml
  hosts: masters
  tasks:
    - name: update master-config.yaml
      replace:
        path: /etc/origin/master/master-config.yaml
        regexp: '^  - challenge((.|\n)*)(HTPasswdPasswordIdentityProvider\n|v1\n|htpasswd\n)'
        replace: |2
            - name: requestheader
              challenge: false
              login: true
              provider:
                apiVersion: v1
                kind: RequestHeaderIdentityProvider
                challengeURL: "{{ mellon_proxy_url }}:{{ mellon_proxy_port }}/proxy/oauth/authorize?${query}"
                loginURL: "{{ mellon_proxy_url }}:{{ mellon_proxy_port }}/proxy/oauth/authorize?${query}"
                clientCA: /etc/httpd/conf.d/lb-0.pem
                headers:
                - X-Remote-User
    - name: restart master-api
      service:
        name: atomic-openshift-master-api
        state: restarted
