---
- name: Install RequestHeader Oauth Config in master-config.yaml
  hosts: masters
  tasks:
    - name: push httpd-saml certificate
      copy:
        src: localhost.pem
        dest: /etc/origin/master/httpd-saml.pem
    - name: remove existing HTPasswd provider
      replace:
        path: /etc/origin/master/master-config.yaml
        regexp: '^  - challenge((.|\n)*)(HTPasswdPasswordIdentityProvider\n|v1\n|htpasswd\n)'
        replace: ''
    - name: update master-config.yaml - add new auth provider
      blockinfile:
        path: /etc/origin/master/master-config.yaml
        insertafter: "identityProviders:"
        block: |2
            - name: requestheader
              challenge: false
              login: true
              provider:
                apiVersion: v1
                kind: RequestHeaderIdentityProvider
                challengeURL: "{{ mellon_proxy_url }}:{{ mellon_proxy_port }}/proxy/oauth/authorize?${query}"
                loginURL: "{{ mellon_proxy_url }}:{{ mellon_proxy_port }}/proxy/oauth/authorize?${query}"
                clientCA: /etc/origin/master/httpd-saml.pem
                headers:
                - X-Remote-User
    - name: restart master-api
      service:
        name: atomic-openshift-master-api
        state: restarted
