---
- name: Install SAML ServiceProvider Client on RH-SSO IdP
  hosts: localhost
  become: no
  tasks:
    - name: install jq
      become: yes
      become_ask: yes
      yum:
        name: jq
        state: latest
    - name: convert mellon metadata xml into rh-sso client json
      shell: |
        access_token=`curl -k -d "client_id=admin-cli" -d "username={{ idp_admin_user }}" --data-urlencode "password={{ idp_admin_password }}" -d "grant_type=password" "{{ idp_url }}/auth/realms/master/protocol/openid-connect/token"| jq -r '.access_token'`
        curl -k -v \
            -H "Authorization: bearer $access_token" \
            -H "Content-Type: application/json;charset=utf-8" \
            --data "@saml2/mellon_metadata.xml" \
            {{ idp_url }}/auth/admin/realms/{{ idp_realm }}/client-description-converter > saml2/mellon-idp-client.json
        jq -s '.[0] * .[1]' saml2/mellon-idp-client.json rh-sso/idp-mappers.json > saml2/mellon-idp-client-with-mappers.json
    - name: upload client json to config map
      command: oc create cm mellon-rh-sso-client --from-file=saml2/mellon-idp-client-with-mappers.json
    - name: mount configmap volume
      command: oc set volume dc/sso -n sso --add --name=mellon-rh-sso-client --mount-path=/mellon-client --type=configmap --configmap-name=mellon-rh-sso-client
    - name: wait for new pods (TODO: improve)
      command: sleep 60
    - name: excute remote kcadm.sh commands in pods 
      shell: |
        POD_NAME=`oc get pods | grep -e "sso.*Running" | head -1 | awk '{print $1}'`
        oc rsh $POD_NAME
        TRUSTSTORE_PASSWORD=`xmllint --xpath "string(/*[namespace-uri()='urn:jboss:domain:5.0' and local-name()='server']/*[namespace-uri()='urn:jboss:domain:5.0' and local-name()='profile']/*[namespace-uri()='urn:jboss:domain:keycloak-server:1.1' and local-name()='subsystem']/*[namespace-uri()='urn:jboss:domain:keycloak-server:1.1' and local-name()='spi' and @name='truststore']/*[namespace-uri()='urn:jboss:domain:keycloak-server:1.1' and local-name()='provider' and @name='file']/*[namespace-uri()='urn:jboss:domain:keycloak-server:1.1' and local-name()='properties']/*[local-name()='property' and @name='password']/@value)" /opt/eap/standalone/configuration/standalone-openshift.xml`
        /opt/eap/bin/kcadm.sh config truststore --trustpass $TRUSTSTORE_PASSWORD /opt/eap/keystores/truststore.jks
        /opt/eap/bin/kcadm.sh config credentials --server https://{{ idp_app_name }}.{{ sso_namespace }}.svc:8443/auth --realm master --user {{ idp_admin_user }} --password {{ idp_admin_password }}
        /opt/eap/bin/kcadm.sh create clients -r {{ ocp_realm }} -f /mellon-client/mellon-idp-client-with-mappers.json
        /opt/eap/bin/kcadm.sh create users -r {{ ocp_realm }} -s username={{ realm_test_user }} -s enabled=true -o --fields id,username
        /opt/eap/bin/kcadm.sh set-password -r {{ ocp_realm }} --username {{ realm_test_user }} --new-password {{ realm_test_user_password }}
