---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: saml-auth
  annotations:
    iconClass: icon-shadowman
    tags: instant-app,saml,authentication
labels:
  template: saml-auth
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: saml-auth
  spec:
    ports:
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      name: saml-auth
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: saml-auth
  spec:
    host: "${APPLICATION_DOMAIN}"
    to:
      kind: Service
      name: saml-auth
    tls:
      termination: passthrough
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: saml-auth
  spec:
    replicas: 1
    selector:
      name: saml-auth
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: saml-auth
        name: saml-auth
      spec:
        containers:
        - env:
          - name: OPENSHIFT_MASTER_PUBLIC_URL
            value: "${OPENSHIFT_MASTER_PUBLIC_URL}"
          - name: APPLICATION_DOMAIN
            value: "${APPLICATION_DOMAIN}"
          - name: PROXY_PATH
            value: "${PROXY_PATH}"
          - name: PROXY_DESTINATION
            value: "${PROXY_DESTINATION}"
          - name: LOG_LEVEL
            value: "${LOG_LEVEL}"
          - name: REMOTE_USER_SAML_ATTRIBUTE
            value: "${REMOTE_USER_SAML_ATTRIBUTE}"
          - name: REMOTE_USER_NAME_SAML_ATTRIBUTE
            value: "${REMOTE_USER_NAME_SAML_ATTRIBUTE}"
          - name: REMOTE_USER_EMAIL_SAML_ATTRIBUTE
            value: "${REMOTE_USER_EMAIL_SAML_ATTRIBUTE}"
          - name: REMOTE_USER_PREFERRED_USERNAME_SAML_ATTRIBUTE
            value: "${REMOTE_USER_PREFERRED_USERNAME_SAML_ATTRIBUTE}"
          image: docker-registry.default.svc:5000/openshift/httpd:2.4
          imagePullPolicy: IfNotPresent
          name: saml-auth
          ports:
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/httpd/saml2
            name: httpd-saml2-config
          - mountPath: /etc/httpd/conf/ose_certs
            name: httpd-ose-certs
          - mountPath: /opt/app-root/httpd-ssl/certs
            name: httpd-server-certs
          - mountPath: /opt/app-root/httpd-ssl/private
            name: httpd-server-key
          - mountPath: /opt/app-root/httpd-ssl/certs/ca
            name: httpd-server-ca-cert
          - mountPath: /etc/httpd/conf.d/openshift.conf
            name: httpd-mellon-conf
          - mountPath: /usr/share/container-scripts/httpd/pre-init/50-update-ServerName.sh
            name: server-name-script
          - mountPath: /etc/httpd/conf.modules.d/11-auth_mellon-debug.conf
            name: debug
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: httpd-saml2-config
          configMap:
            defaultMode: 420
            name: httpd-saml2-config
        - name: httpd-ose-certs
          secret:
            defaultMode: 420
            secretName: httpd-ose-certs-secret
        - name: httpd-server-certs
          secret:
            defaultMode: 420
            secretName: httpd-server-cert-secret
        - name: httpd-server-key
          secret:
            defaultMode: 420
            secretName: httpd-server-key-secret
        - name: httpd-server-ca-cert
          secret:
            defaultMode: 420
            secretName: httpd-server-ca-cert-secret
        - configMap:
            defaultMode: 420
            name: httpd-mellon-conf
          name: httpd-mellon-conf
        - configMap:
            defaultMod: 420
            name: server-name-script
          name: server-name-script
        - configMap:
            defaultMod: 420
            name: debug
          name: debug
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - saml-auth
        from:
          kind: ImageStreamTag
          name: httpd:2.4
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: saml-service-provider
    name: saml-service-provider
  spec:
    lookupPolicy:
      local: false
parameters:
- name: OPENSHIFT_MASTER_PUBLIC_URL
  description: OpenShift Master Public URL
- name: APPLICATION_DOMAIN
  description: The exposed hostname that will route to the SAML service, if left blank
    a value will be defaulted.
- name: PROXY_PATH
  description: The root path that will proxy to the OpenShift Enterprise OAuth server,
    with a trailing slash (e.g. /oauth/)
  required: true
- name: PROXY_DESTINATION
  description: The full URL, including port and path, with a trailing slash, that
    the PROXY_PATH should proxy (e.g. https://api.example.com:8443/oauth/)
  required: true
- name: LOG_LEVEL
  description: Logging level for mod_auth_mellon
  value: info
- name: REMOTE_USER_SAML_ATTRIBUTE
  description: IdP SAML attribute for the user identity.
  required: true
- name: REMOTE_USER_NAME_SAML_ATTRIBUTE
  description: IdP SAML attribute for a display name.
  required: true
- name: REMOTE_USER_EMAIL_SAML_ATTRIBUTE
  description: IdP SAML attribute for an email address.
  required: true
- name: REMOTE_USER_PREFERRED_USERNAME_SAML_ATTRIBUTE
  description: IdP SAML attribute for a preferred user name, if different than the immutable identity determined from the headers specified in headers.
  required: true
