---
- name: Install RequestHeader Oauth Config in master-config.yaml
  hosts: masters
  tasks:
    - name: remove existing HTPasswd provider
      replace:
        path: /etc/origin/master/master-config.yaml
        regexp: '^  - challenge((.|\n)*)(HTPasswdPasswordIdentityProvider\n|v1\n|htpasswd\n)'
        replace: ''
      when: ansible_facts['remove_htpasswd_provider'] == true
    - name: update master-config.yaml - add new auth provider
      blockinfile:
        path: /etc/origin/master/master-config.yaml
        insertafter: "identityProviders:"
        block: |2
            - name: SAML
              challenge: false
              login: true
              provider:
                apiVersion: v1
                kind: RequestHeaderIdentityProvider
                loginURL: "{{ saml_auth_url }}/oauth/authorize?${query}"
                clientCA: /etc/origin/master/ca.crt
                headers:
                - X-Remote-User
                - Remote-User
                emailHeaders:
                - X-Remote-User-Email
                - Remote-User-Email
                nameHeaders:
                - X-Remote-User-Name
                - Remote-User-Name
                preferredUsernameHeaders:
                - X-Remote-User-Preferred-Username
                - Remote-User-Preferred-Username
    - name: Populate service facts
      service_facts:
    - name: restart master-api
      service:
        name: atomic-openshift-master-api
        state: restarted
      when: "'atomic-openshift-master-api' in services"
    - name: restart master-api containerized
      command: /usr/local/bin/master-restart api
      when: "'atomic-openshift-master-api' not in services"
